"""
The test_list contains the elements needed to make the task prompts for the different conditions.
If you want to change the tasks or add tasks, you can easily do so by changing this list.

The source_tool is the object typically used for the task. The afforded_tool is the correct option.
The associated tools are objects associated with the source_tool and task, but inappropriate for the task.
The irrelevant tools are just that, irrelevant to the task. They are distractor options.
"""


test_list = [
    {
        "q_number": "Q1",
        "task": "keep your body warm",
        "source_tool": "a jacket",
        "afforded_tool": "curtains",
        "associated_tool1": "an umbrella",
        "associated_tool2": "a boxer shorts",
        "associated_tool3": "a baseball cap",
        "associated_tool4": "leather gloves",
        "irrelevant_tool1": "a bowl",
        "irrelevant_tool2": "a charger",
        "irrelevant_tool3": "a crayon",
        "irrelevant_tool4": "a letter opener"
    },
    {
        "q_number": "Q2",
        "task": "dig a hole",
        "source_tool": "a spade",
        "afforded_tool": "a table tennis racket",
        "associated_tool1": "a rake",
        "associated_tool2": "a garden hose",
        "associated_tool3": "a wheelbarrow",
        "associated_tool4": "a lawnmower",
        "irrelevant_tool1": "a drying rack",
        "irrelevant_tool2": "a notebook",
        "irrelevant_tool3": "a lighter",
        "irrelevant_tool4": "an eraser"
    },
    {
        "q_number": "Q3",
        "task": "hammer a nail",
        "source_tool": "a hammer",
        "afforded_tool": "a saucepan",
        "associated_tool1": "a screwdriver",
        "associated_tool2": "a saw",
        "associated_tool3": "a meter stick",
        "associated_tool4": "a chisel",
        "irrelevant_tool1": "a picture frame",
        "irrelevant_tool2": "a bicycle wheel",
        "irrelevant_tool3": "a jug",
        "irrelevant_tool4": "a nail clipper"
    },
    {
        "q_number": "Q4",
        "task": "transport water",
        "source_tool": "a glass",
        "afforded_tool": "a swimming cap",
        "associated_tool1": "a plate",
        "associated_tool2": "a fork",
        "associated_tool3": "a flour sifter",
        "associated_tool4": "a napkin",
        "irrelevant_tool1": "rubber bands",
        "irrelevant_tool2": "a hairbrush",
        "irrelevant_tool3": "a flashlight",
        "irrelevant_tool4": "a shoehorn"
    },
    {
        "q_number": "Q5",
        "task": "cut a cucumber into cubes",
        "source_tool": "a kitchen knife",
        "afforded_tool": "a ruler",
        "associated_tool1": "a peeler",
        "associated_tool2": "a whisk",
        "associated_tool3": "a mortar and pestle",
        "associated_tool4": "a potato masher",
        "irrelevant_tool1": "an ash tray",
        "irrelevant_tool2": "a dustpan",
        "irrelevant_tool3": "a plastic bag",
        "irrelevant_tool4": "a fly swatter"
    },
    {
        "q_number": "Q6",
        "task": "rest your head",
        "source_tool": "a small pillow",
        "afforded_tool": "a kitchen roll",
        "associated_tool1": "a sleep mask",
        "associated_tool2": "a bedside table",
        "associated_tool3": "a sleeping pill",
        "associated_tool4": "a pillow case",
        "irrelevant_tool1": "a book",
        "irrelevant_tool2": "a compass",
        "irrelevant_tool3": "a corkscrew",
        "irrelevant_tool4": "a crutch"
    },
    {
        "q_number": "Q7",
        "task": "sweep the floor",
        "source_tool": "a broom",
        "afforded_tool": "a wig",
        "associated_tool1": "laundry detergent",
        "associated_tool2": "a bucket",
        "associated_tool3": "a broom holder",
        "associated_tool4": "a spray bottle",
        "irrelevant_tool1": "a vase",
        "irrelevant_tool2": "a baking tray",
        "irrelevant_tool3": "an envelope",
        "irrelevant_tool4": "a salt shaker"
    },
    {
        "q_number": "Q8",
        "task": "draw a straight line",
        "source_tool": "a ruler",
        "afforded_tool": "a DVD case",
        "associated_tool1": "paperclips",
        "associated_tool2": "a pencil sharpener",
        "associated_tool3": "a staple remover",
        "associated_tool4": "correction tape",
        "irrelevant_tool1": "a plant pot",
        "irrelevant_tool2": "a razor",
        "irrelevant_tool3": "a pepper mill",
        "irrelevant_tool4": "a shoe"
    },
    {
        "q_number": "Q9",
        "task": "take a baked and hot cake out of the oven",
        "source_tool": "a pair of oven mittens",
        "afforded_tool": "a beach towel",
        "associated_tool1": "a chef's hat",
        "associated_tool2": "a saucepan lid",
        "associated_tool3": "a measuring cup",
        "associated_tool4": "a cheese knife",
        "irrelevant_tool1": "a balloon",
        "irrelevant_tool2": "a paintbrush",
        "irrelevant_tool3": "a needle",
        "irrelevant_tool4": "a candle"
    },
    {
        "q_number": "Q10",
        "task": "roll out a pizza dough",
        "source_tool": "a rolling pin",
        "afforded_tool": "a baseball bat",
        "associated_tool1": "a pizza cutter",
        "associated_tool2": "a measuring spoon",
        "associated_tool3": "a pastry brush",
        "associated_tool4": "a garlic press",
        "irrelevant_tool1": "a backpack",
        "irrelevant_tool2": "a crowbar",
        "irrelevant_tool3": "a comb",
        "irrelevant_tool4": "a jewellery box"
    },
    {
        "q_number": "Q11",
        "task": "fasten gift wrapping paper around a gift",
        "source_tool": "scotch tape",
        "afforded_tool": "fishing line",
        "associated_tool1": "scissors",
        "associated_tool2": "a rubber stamp",
        "associated_tool3": "a notepad",
        "associated_tool4": "a quill pen",
        "irrelevant_tool1": "chopsticks",
        "irrelevant_tool2": "a tablecloth",
        "irrelevant_tool3": "a whiteboard sponge",
        "irrelevant_tool4": "a bicycle pump"
    },
    {
        "q_number": "Q12",
        "task": "write down a short note",
        "source_tool": "a post-it note",
        "afforded_tool": "a coffee filter",
        "associated_tool1": "an ink cartridge",
        "associated_tool2": "a glue stick",
        "associated_tool3": "a hole puncher",
        "associated_tool4": "a stapler",
        "irrelevant_tool1": "a toothbrush",
        "irrelevant_tool2": "a helmet",
        "irrelevant_tool3": "a pair of skis",
        "irrelevant_tool4": "sunglasses"
    },
    {
        "q_number": "Q13",
        "task": "serve fruit on a plate",
        "source_tool": "a serving plate",
        "afforded_tool": "a frisbee",
        "associated_tool1": "an apple slicer",
        "associated_tool2": "a juice carton",
        "associated_tool3": "a blender",
        "associated_tool4": "an ice cream scoop",
        "irrelevant_tool1": "a duffel bag",
        "irrelevant_tool2": "a map",
        "irrelevant_tool3": "a scythe",
        "irrelevant_tool4": "a teddy bear"
    },
    {
        "q_number": "Q14",
        "task": "fasten a piece of paper to a wall",
        "source_tool": "Blu Tack",
        "afforded_tool": "plasters",
        "associated_tool1": "a folder",
        "associated_tool2": "rubber bands",
        "associated_tool3": "a whiteboard",
        "associated_tool4": "a pen",
        "irrelevant_tool1": "boots",
        "irrelevant_tool2": "a water bottle",
        "irrelevant_tool3": "a wrench",
        "irrelevant_tool4": "a bar soap"
    },
    {
        "q_number": "Q15",
        "task": "practice doing baseball tosses with a friend",
        "source_tool": "a baseball",
        "afforded_tool": "an apple",
        "associated_tool1": "a basketball",
        "associated_tool2": "a bowling ball",
        "associated_tool3": "a table tennis ball",
        "associated_tool4": "a volleyball",
        "irrelevant_tool1": "a broom",
        "irrelevant_tool2": "a blanket",
        "irrelevant_tool3": "a bed sheet",
        "irrelevant_tool4": "a thermos"
    },
    {
        "q_number": "Q16",
        "task": "keep your ears warm",
        "source_tool": "a beanie",
        "afforded_tool": "an audio headset",
        "associated_tool1": "skiing glasses",
        "associated_tool2": "winter gloves",
        "associated_tool3": "socks",
        "associated_tool4": "fur boots",
        "irrelevant_tool1": "a keychain",
        "irrelevant_tool2": "a padlock",
        "irrelevant_tool3": "a grater",
        "irrelevant_tool4": "tweezers"
    },
    {
        "q_number": "Q17",
        "task": "replace a missing king piece on a chess board",
        "source_tool": "the king piece",
        "afforded_tool": "a one pound coin",
        "associated_tool1": "a sceptre",
        "associated_tool2": "a crown",
        "associated_tool3": "an orb",
        "associated_tool4": "a throne",
        "irrelevant_tool1": "a coffee cup",
        "irrelevant_tool2": "a CD disk",
        "irrelevant_tool3": "a brick",
        "irrelevant_tool4": "a ladder"
    },
    {
        "q_number": "Q18",
        "task": "beat the dust out of a rug",
        "source_tool": "a rug beater",
        "afforded_tool": "a tennis racket",
        "associated_tool1": "a sponge",
        "associated_tool2": "a feather duster",
        "associated_tool3": "a stain remover",
        "associated_tool4": "a clothespin",
        "irrelevant_tool1": "a matchbox",
        "irrelevant_tool2": "a button",
        "irrelevant_tool3": "a mirror",
        "irrelevant_tool4": "a hand watch"
    },
    {
        "q_number": "Q19",
        "task": "mark where you are in a book",
        "source_tool": "a bookmark",
        "afforded_tool": "a shoelace",
        "associated_tool1": "a highlighter",
        "associated_tool2": "a book stand",
        "associated_tool3": "a library catalogue",
        "associated_tool4": "a reading lamp",
        "irrelevant_tool1": "a chopping board",
        "irrelevant_tool2": "a belt",
        "irrelevant_tool3": "a pushpin",
        "irrelevant_tool4": "a magnifying glass"
    },
    {
        "q_number": "Q20",
        "task": "carry laundry from one place to another",
        "source_tool": "a laundry basket",
        "afforded_tool": "a picnic blanket",
        "associated_tool1": "a toiletry bag",
        "associated_tool2": "a hanger",
        "associated_tool3": "an iron",
        "associated_tool4": "fabric softener",
        "irrelevant_tool1": "a can opener",
        "irrelevant_tool2": "a lunchbox",
        "irrelevant_tool3": "a wallet",
        "irrelevant_tool4": "a toothpick"
    }
]
